ARG IMAGE_BASE="registry.access.redhat.com/ubi9/ubi"
ARG IMAGE_TAG="9.6"

ARG RUNTIME_IMAGE

FROM ${RUNTIME_IMAGE} AS apisix-runtime
FROM ${IMAGE_BASE}:${IMAGE_TAG}

COPY ./scripts/install-common.sh /install-common.sh
COPY ./scripts/determine-dist.sh /determine-dist.sh
COPY --from=apisix-runtime /usr/local/openresty /usr/local/openresty

ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

ARG iteration="0"
ARG apisix_repo="https://github.com/apache/apisix"
ARG checkout_v
ARG IMAGE_BASE
ARG IMAGE_TAG
ARG CODE_PATH

# install dependencies
# libyaml-devel lives in the CRB (CodeReady Builder, aka PowerTools) repo on
# el8, which is disabled by default in the rockylinux:8 image. Use
# --enablerepo directly: the image lacks the config-manager dnf plugin.
RUN yum install -y --enablerepo=powertools libyaml-devel
RUN /install-common.sh install_apisix_dependencies_rpm

ENV checkout_v=${checkout_v}
ENV iteration=${iteration}
ENV apisix_repo=${apisix_repo}
ENV IMAGE_BASE=${IMAGE_BASE}
ENV IMAGE_TAG=${IMAGE_TAG}

COPY ${CODE_PATH} /apisix

# install apisix
RUN /install-common.sh install_apisix \
    # determine dist and write it into /tmp/dist file
    && /determine-dist.sh
